######################################################################
# Automatically generated by qmake (3.0) ?? 1? 21 11:47:22 2015
######################################################################

TEMPLATE = app
TARGET = quit
INCLUDEPATH += .

# Input
SOURCES += test.cpp

QT += gui core network qml quick widgets sql xml
