######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 16 17:16:57 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += application.qrc
