######################################################################
# Automatically generated by qmake (3.0) ?? 1? 21 11:48:19 2015
######################################################################

TEMPLATE = app
TARGET = finddialog
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp

QT += widgets gui core
