######################################################################
# Automatically generated by qmake (3.0) ?? 1? 21 11:47:05 2015
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
QT += gui core network qml quick widgets sql xml
