######################################################################
# Automatically generated by qmake (3.0) ?? 1? 20 17:40:14 2015
######################################################################

TEMPLATE = app
TARGET = ageChoick
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += gui core network qml quick widgets sql xml
