######################################################################
# Automatically generated by qmake (3.0) ?? 1? 21 11:53:21 2015
######################################################################

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
QT += gui core network qml quick widgets sql xml
