######################################################################
# Automatically generated by qmake (3.0) ?? 1? 21 13:41:53 2015
######################################################################

TEMPLATE = app
TARGET = find
INCLUDEPATH += .

# Input
HEADERS += find.h
SOURCES += find.cpp main.cpp
QT += gui core network qml quick widgets sql xml
